use_frameworks!

target 'JSLTransitionLib_Example' do
  platform :ios, '9.0'

  pod 'JSLTransitionLib', :path => '../'

  target 'JSLTransitionLib_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  end
end
